groups:
  - name: example
    rules:
      - alert: PacketLoss > 0
        expr: ping_percent_packet_loss != 0
        for: 2m
        labels:
          severity: urgent
        annotations:
          description: packet loss to {{ $labels.url }} has reached {{ $value }}%
      - alert: net_input_rate_bps > 2000
        expr: demo_recording_net_rate_bps > 2000
        for: 2m
        labels:
          severity: warn
        annotations:
          description: Net input rate for interface {{ $labels.interface }} has reached {{ $value }} bps
