global:
  scrape_interval: 10s
  evaluation_interval: 15s

rule_files:
  - rules/alert_rules.yml
  - rules/recording_rules.yml

scrape_configs:
  - job_name: "telegraf"
    static_configs:
      - targets:
          - telegraf:9273
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093
