global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "telegraf"
    static_configs:
      - targets: ["telegraf-1:9273", "telegraf-2:9274"]
  - job_name: "python-exporter"
    static_configs:
      - targets: ["python-exporter:8000"]
  - job_name: "pushgateway"
    static_configs:
      - targets: ["pushgateway:9091"]
